# # version: '3.7'

# # services:
# #   proxy:
# #     image: nginx:alpine
# #     container_name: proxy
# #     ports:
# #       - '80:80'
# #     volumes:
# #       - ./nginx.conf:/etc/nginx/nginx.conf
# #     restart: 'unless-stopped'
# #     networks:
# #       - backend
# #   server:
# #     build:
# #       context: ./
# #       target: development-build-stage
# #       dockerfile: Dockerfile
# #     container_name: server
# #     ports:
# #       - '5000:5000'
# #     environment:
# #       MONGO_HOST: mongo
# #       MONGO_PORT: 27017
# #       MONGO_DATABASE: mongoose
# #     volumes:
# #       - ./:/app
# #       - /app/node_modules
# #     restart: 'unless-stopped'
# #     networks:
# #       - backend
# #     links:
# #       - mongo
# #     depends_on:
# #       - mongo
# #   mongo:
# #     image: mvertes/alpine-mongo
# #     container_name: mongo
# #     ports:
# #       - '27017:27017'
# #     networks:
# #       - backend

# # networks:
# #   backend:
# #     driver: bridge

# # volumes:
# #   data:
# #     driver: local
# # Set the version of docker compose to use
# version: "3.9"

# # The containers that compose the project
# services:
#   db:
#     image: postgres:13
#     restart: always
#     container_name: integration-tests-prisma
#     ports:
#       - "5433:5432"
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#       POSTGRES_DB: tests
#       DATABASE_URL: "postgresql://prisma:prisma@localhost:5433/tests"
version: "3.7"

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://prisma:prisma@localhost:5433/tests?schema=public
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma
    expose:
      - 5433
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
      DATABASE_URL: "postgresql://prisma:prisma@localhost:5433/tests"
    networks:
      - backend

  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
